### ISSUE TITLE
Error on workflow page

### ISSUE THREAD

**Issue by flibustenet** [nive/nive_cms#15]
On the edit board, on the list of sub-pages the workflow button (if the subpage is not published) raise an error

```
TypeError: argument of type 'NoneType' is not iterable

 - Expression: "view.cmsIndex_tmpl().macros['main']"
 - Filename:   ... nive2/nive_cms/nive_cms/workflow/templates/editorpage.pt
 - Location:   (line 2: col 28)
 - Source:     ... l:use-macro="view.cmsIndex_tmpl().macros['main']" i18n:domai ...
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  wf: {...} (7)
               head: 
               repeat: {...} (0)
               renderer_name: nive_cms.workflow:templates/editorpage.pt
               cmsview: <_factory_WorkflowEdit - at 0x347cf90>
               renderer_info: <RendererHelper - at 0x3089b50>
               result: True
               req: <Request - at 0x40dde50>
               request: <Request - at 0x40dde50>
               content: 
               context: <_factory_page hu at 0x3370050>
               view: <_factory_WorkflowEdit - at 0x347cf90>
```
